spring:  
  #http:
  #  multipart:
  #    enabled: true
  #    max-file-size: 1000MB
  #    max-request-size: 1000MB

  #servlet:
  #  multipart:
  #    enabled: true
  #    max-file-size: 1000M  #单个文件的最大上限
  #    max-request-size: 1000M #单个请求的文件总大小上限
dubbo: 
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: CallFileSystemServiceImplConsumer
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.1.6:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20880
    dubbo:
    payload: 1048576000
  #scan: com.cluster.Service.interfaces.callFileService.impl  #服务暴露与发现消费所在的package 